//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task78_Sequences.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Task78_Sequences.Resources.MessagesResources", typeof(MessagesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fibonacci sequence from {0} to {1}: .
        /// </summary>
        internal static string FibonacciAnswer {
            get {
                return ResourceManager.GetString("FibonacciAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This application generate the number sequence depending on algorythms choosen:
        ///if 1 argument - Pow mode,
        ///if 2 arguments - Fibonacci mode.
        /// </summary>
        internal static string instruction {
            get {
                return ResourceManager.GetString("instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid argument 1. Enter integer number from -2 147 483 648 to 2 147 483 648.
        /// </summary>
        internal static string InvalidArgument1 {
            get {
                return ResourceManager.GetString("InvalidArgument1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid argument 2. Enter integer number from -2 147 483 648 to 2 147 483 648.
        /// </summary>
        internal static string InvalidArgument2 {
            get {
                return ResourceManager.GetString("InvalidArgument2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The upper limit value must be greater than lower.
        /// </summary>
        internal static string InvalidArgumentFiboMixLimits {
            get {
                return ResourceManager.GetString("InvalidArgumentFiboMixLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The upper limit value must be greater than 0.
        /// </summary>
        internal static string InvalidArgumentFiboNegative {
            get {
                return ResourceManager.GetString("InvalidArgumentFiboNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The upper limit value must be greater than 0.
        /// </summary>
        internal static string InvalidArgumentPowNegative {
            get {
                return ResourceManager.GetString("InvalidArgumentPowNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pow sequence from {0} to {1}: .
        /// </summary>
        internal static string PowAnswer {
            get {
                return ResourceManager.GetString("PowAnswer", resourceCulture);
            }
        }
    }
}
